version: '3.8'

services:
  server1:
    container_name: pendulum-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    volumes:
      - .:/app
    command: npm run dev

  server2:
    container_name: pendulum-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    volumes:
      - .:/app
    command: npm run dev

  server3:
    container_name: pendulum-3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    volumes:
      - .:/app
    command: npm run dev

  server4:
    container_name: pendulum-4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
    volumes:
      - .:/app
    command: npm run dev

  server5:
    container_name: pendulum-5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
    volumes:
      - .:/app
    command: npm run dev
