version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./libs/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Mount the config file

  server1:
    container_name: pendulum-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MQTT_BROKER=mqtt-broker     # Use service name
      - MQTT_PORT=1883
    volumes:
      - .:/app
    command: npm run dev

  server2:
    container_name: pendulum-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MQTT_BROKER=mqtt-broker     # Use service name
      - MQTT_PORT=1883
    volumes:
      - .:/app
    command: npm run dev

  server3:
    container_name: pendulum-3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MQTT_BROKER=mqtt-broker     # Use service name
      - MQTT_PORT=1883
    volumes:
      - .:/app
    command: npm run dev

  server4:
    container_name: pendulum-4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MQTT_BROKER=mqtt-broker     # Use service name
      - MQTT_PORT=1883
    volumes:
      - .:/app
    command: npm run dev

  server5:
    container_name: pendulum-5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - MQTT_BROKER=mqtt-broker     # Use service name
      - MQTT_PORT=1883
    volumes:
      - .:/app
    command: npm run dev
